;;; (mfem) — umbrella module re-exporting all MFEM bindings.
;;;
;;; Usage:
;;;   (use-modules (mfem))
;;;
;;; Individual modules can be cherry-picked for faster load times:
;;;   (use-modules (mfem vector) (mfem mesh))

(define-module (mfem)
  #:duplicates (merge-generics replace warn-override-core warn last))

(use-modules (mfem mem_manager)
             (mfem globals)
             (mfem array)
             (mfem vector)
             (mfem operators)
             (mfem matrix)
             (mfem densemat)
             (mfem sparsemat)
             (mfem intrules)
             (mfem eltrans)
             (mfem fe)
             (mfem symmat)
             (mfem integrator)
             (mfem nonlininteg)
             (mfem coefficient)
             (mfem mesh)
             (mfem fe_coll)
             (mfem fespace)
             (mfem gridfunc)
             (mfem lininteg)
             (mfem bilininteg)
             (mfem linearform)
             (mfem handle)
             (mfem bilinearform)
             (mfem solvers)
             (mfem sparsesmoothers)
             (mfem device))

;; Re-export all public bindings from the imported modules.
(let ((public-i (module-public-interface (current-module))))
  (for-each
    (lambda (mod)
      (module-for-each
        (lambda (name var)
          (module-add! public-i name var))
        (resolve-interface mod)))
    '((mfem mem_manager)
      (mfem globals)
      (mfem array)
      (mfem vector)
      (mfem operators)
      (mfem matrix)
      (mfem densemat)
      (mfem sparsemat)
      (mfem intrules)
      (mfem eltrans)
      (mfem fe)
      (mfem symmat)
      (mfem integrator)
      (mfem nonlininteg)
      (mfem coefficient)
      (mfem mesh)
      (mfem fe_coll)
      (mfem fespace)
      (mfem gridfunc)
      (mfem lininteg)
      (mfem bilininteg)
      (mfem linearform)
      (mfem handle)
      (mfem bilinearform)
      (mfem solvers)
      (mfem sparsesmoothers)
      (mfem device))))
